spring:
  datasource:
    url: jdbc:mysql://139.196.30.186:3306/fastdfs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: lvym
    password: tbny1312
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false  #去除thymeleaf缓存
    mode: LEGACYHTML5 #忽略HTML5语法校验
  servlet:
    multipart:
      max-file-size: 1000000000  #默认单位似乎是字节  #????springmvc单个文件大小  默认1m
#      max-request-size: 10     #form表单传递过来总文件大小  默认10m
#spring????Mybatis????
mybatis:
  base-packages: com.lvym.fdfs.pojo #pojo别名
  mapper-locations: classpath:mapper/*Mapper.xml   #????Mybatis??????



